### ISSUE TITLE
"Could not locate Gemfile"

### ISSUE THREAD

**Issue by b0g3r** [dependabot/dependabot-script#221]
I try using dependabot-core on my python project in gitlab on demand.
My .gitlab-ci.yaml:
```yaml
image: python:3.6
...

checks:dependabot:
  image: dependabot/dependabot-core
  variables:
    PACKAGE_MANAGER: "pip"
  before_script:
    - bundle install -j $(nproc) --path vendor
  script: bundle exec ruby ./generic-update-script.rb
  cache:
    paths:
      - vendor/
  only:
    - schedules
```
I add schedule config like on screenshot
![image](https://user-images.githubusercontent.com/19777948/53555650-64254800-3b53-11e9-8cc2-2c846fe2fef7.png)

Log of job:
```
Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on example-python-project [gitlab-ci-runner-4] (66f6e160)
Using Docker executor with image dependabot/dependabot-core ...
Using docker image sha256:f21c27b19825abb017667311022bdb37ce98755a8ef39ea6784295bc1e57792f for predefined container...
Pulling docker image dependabot/dependabot-core ...
Using docker image dependabot/dependabot-core ID=sha256:7063dfbd3d5bce196107a274a87228451a052a2158858feb4593e6c1940308a8 for build container...
Running on runner-66f6e160-project-35-concurrent-2 via gitlab-ci-runner-4...
Fetching changes...
Removing .bundle/
HEAD is now at 2d4ac36 Add dependabot
From https://gitlab.example.net/backend/example-python-project
   2d4ac36..a4a3d9b  branch       -> origin/branch
Checking out a4a3d9ba as branch...
Skipping Git submodules setup
Checking cache for default...
Successfully extracted cache
$ bundle install -j $(nproc) --path vendor
Could not locate Gemfile
```

Any ideas?
