### ISSUE TITLE
Unable to find Python Requirements.txt in ADO

### ISSUE THREAD

**Issue by dciborow** [dependabot/dependabot-script#487]
I am trying to leverage depandabot in my Azure DevOps repo. 

I keep thinking that my issue is rooted in the fact that my ADO is not defaulted to the new URL format. So our URL is "https://msorg.visualstudio.com/msproject", not "https://dev.visualstudio.com/msorg/msproject". But, my errors seem better sticking with "dev.visualstudio.com". 

So far I get the following two outputs. 
Fetching pip dependency files for msazure/One/_git/AGAI-IndustryAI-Template
Parsing dependencies information

Then big error block. 
```
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.111.59/lib/dependabot/shared_helpers.rb:117:in `rescue in run_helper_subprocess': Dependabot::SharedHelpers::HelperSubprocessFailed
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.111.59/lib/dependabot/shared_helpers.rb:85:in `run_helper_subprocess'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-python-0.111.59/lib/dependabot/python/file_parser.rb:152:in `block in parsed_requirement_files'

/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/json/common.rb:156:in `parse'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.111.59/lib/dependabot/shared_helpers.rb:109:in `run_helper_subprocess'
```

```python
# This script is designed to loop through all dependencies in a GHE, GitLab or
# Azure DevOps project, creating PRs where necessary.

require "dependabot/file_fetchers"
require "dependabot/file_parsers"
require "dependabot/update_checkers"
require "dependabot/file_updaters"
require "dependabot/pull_request_creator"
require "dependabot/omnibus"
require "gitlab"

azure_hostname = ENV["AZURE_HOSTNAME"] || "dev.azure.com"

credentials = [
  {
    "type" => "git_source",
    "host" => azure_hostname,
    "username" => "x-access-token",
    "password" => ENV["SYSTEM_ACCESSTOKEN"]
  }
]

# Full name of the repo you want to create pull requests for.
repo_name = ENV["PROJECT_PATH"] || "msazure/One/_git/AGAI-IndustryAI-Template" # namespace/project

# Directory where the base dependency files are.
directory = ENV["DIRECTORY_PATH"] || "/"

# Name of the package manager you'd like to do the update for. Options are:
package_manager = ENV["PACKAGE_MANAGER"] || "pip"


source = Dependabot::Source.new(
  provider: "azure",
  hostname: azure_hostname,
  api_endpoint: "https://#{azure_hostname}/",
  repo: repo_name,
  directory: directory,
  branch: "dciborow/dependabot",
)

##############################
# Fetch the dependency files #
##############################
puts "Fetching #{package_manager} dependency files for #{repo_name}"
fetcher = Dependabot::FileFetchers.for_package_manager(package_manager).new(
  source: source,
  credentials: credentials,
)

files = fetcher.files
commit = fetcher.commit
```

Azure Pipeline calling update.rb

```yaml
trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '=2.6'

- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
    curl https://pyenv.run | bash
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    export DEPENDABOT_NATIVE_HELPERS_PATH="$(pwd)/native-helpers"
    mkdir -p $DEPENDABOT_NATIVE_HELPERS_PATH/{terraform,python,dep,go_modules,hex,composer,npm_and_yarn}
    export PATH="$PATH:$DEPENDABOT_NATIVE_HELPERS_PATH/terraform/bin:$DEPENDABOT_NATIVE_HELPERS_PATH/python/bin:$DEPENDABOT_NATIVE_HELPERS_PATH/go_modules/bin:$DEPENDABOT_NATIVE_HELPERS_PATH/dep/bin"
    export MIX_HOME="$DEPENDABOT_NATIVE_HELPERS_PATH/hex/mix"

    cp -r $(bundle show dependabot-python)/helpers $DEPENDABOT_NATIVE_HELPERS_PATH/python/helpers

    $DEPENDABOT_NATIVE_HELPERS_PATH/python/helpers/build $DEPENDABOT_NATIVE_HELPERS_PATH/python

    bundle exec ruby update.rb
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    ob_restore_phase: true
  displayName: 'Update dependencies'
```
