### ISSUE TITLE
GitLab CI setup completely broken

### ISSUE THREAD

**Issue by tmaier** [dependabot/dependabot-script#657]
There are multiple issues with the current GitLab CI setup (`.gitlab-ci.example.yml`), which make it impossible to use it at the moment.

1. The `build-image` does not define a image to use.  This means `docker build` fails, as the default image `ruby:2.5` does of course not have a docker executable at-hand
2. It is actually a so called "docker-in-docker" use case. The `build-image` step currently only builds the image, but it does not push the image to the local repository
3. All jobs extending `.dependabot` are currently referencing the Dockerhub image `dependabot/dependabot-script` it does not reference the image intended to build and to push to the local GitLab Docker registry
4.  Items (1), (2) and (3) above should be obsolete at all in the base case, as the image `dependabot/dependabot-script` could be built directly from within this repository and be made available for use for all at Dockerhub. This would safe more resource efficient for all
5. The Docker image built is rather big. The base image itself is currently 1.13 GB, the image built is shocking 4.42GB

**Comment by Nothing4You** [comment]
related to https://github.com/dependabot/dependabot-core/issues/946

**Comment by Nothing4You** [comment]
fwiw i'm currently building it like this with a non-gitlab registry, something broke after upgrading to a version higher than 0.152.0 though:

```diff
diff --git a/.gitlab-ci.example.yml b/.gitlab-ci.yml
index f050d40..7d4d249 100644
--- a/.gitlab-ci.example.yml
+++ b/.gitlab-ci.yml
@@ -16,12 +16,20 @@
 # https://docs.gitlab.com/ee/ci/yaml/

 build-image:
+  interruptible: true
   stage: build
+  image:
+    name: gcr.io/kaniko-project/executor:debug
+    entrypoint: [""]
   script:
-    - docker build -t "dependabot/dependabot-script" -f Dockerfile .
+    - mkdir -p /kaniko/.docker
+    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
+    - /kaniko/executor --reproducible --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_PROJECT_NAME:latest
+  rules:
+    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'

 .dependabot:
-  image: dependabot/dependabot-script
+  image: myregistry/dependabot-script
   variables:
     PACKAGE_MANAGER: $CI_JOB_NAME
   script:
```

**Comment by Nothing4You** [comment]
this version works with 0.154.0+:

```diff
diff --git a/.gitlab-ci.example.yml b/.gitlab-ci.yml
index f050d40..e2247d3 100644
--- a/.gitlab-ci.example.yml
+++ b/.gitlab-ci.yml
@@ -16,15 +16,25 @@
 # https://docs.gitlab.com/ee/ci/yaml/

 build-image:
+  interruptible: true
   stage: build
+  image:
+    name: gcr.io/kaniko-project/executor:debug
+    entrypoint: [""]
   script:
-    - docker build -t "dependabot/dependabot-script" -f Dockerfile .
+    - mkdir -p /kaniko/.docker
+    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
+    - /kaniko/executor --reproducible --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_PROJECT_NAME:latest
+  rules:
+    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'

 .dependabot:
-  image: dependabot/dependabot-script
+  image: myregistry/dependabot-script
   variables:
     PACKAGE_MANAGER: $CI_JOB_NAME
   script:
+    # switch to dependabot base dir, as gitlab switches to the directory where the project repo resides
+    - cd /home/dependabot/dependabot-script
     - bundle exec ruby ./generic-update-script.rb
   only:
     - schedules
```

primary difference to my previous ci config is changing to the dependabot-script directory in the container.

by having a standalone docker image built from this it's also easy to run dependabot jobs on other repos instead of having everything configured in the dependabot repo.

example repo config i'm using (i'm specifying the package managers in the ci config directly instead of env vars as that's just not needed):

`.gitlab-ci.yml`
```yml

# include dependabot in stages along with other stages you may have
stages:
  - build
  - dependabot

.dependabot:
  image: myregistry/dependabot-script
  stage: dependabot
  variables:
    PACKAGE_MANAGER: $CI_JOB_NAME
    PROJECT_PATH: $CI_PROJECT_PATH
  script:
    # switch to dependabot base dir, as gitlab switches to the directory where the project repo resides
    - cd /home/dependabot/dependabot-script
    - bundle exec ruby ./generic-update-script.rb
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

docker:
  extends: .dependabot

npm_and_yarn:
  extends: .dependabot
  # patched generic-update-script.rb to be able to pass credentials
  variables:
    DEPENDABOT_NPM_REGISTRY_URL: $CI_API_V4_URL/packages/npm/
    DEPENDABOT_NPM_REGISTRY_TOKEN: $CI_JOB_TOKEN
```

this example runs in my environment with a single dependabot schedule with the following env vars:
- GITHUB_ACCESS_TOKEN
- GITLAB_HOSTNAME
- GITLAB_ACCESS_TOKEN (i usually create the project/group specific)
