### ISSUE TITLE
ignore gomod dependency is not working

### ISSUE THREAD

**Issue by fahedouch** [dependabot/dependabot-script#826]
Hi guys

I want to ignore some private dependency within the  go.mod package 

abstract from my `gomod` package
```
module xxxxx-api

go 1.18

require (
	dev.azure.com/xxx/xxx-sdk-common-api.git v1.1.1
	github.com/agext/levenshtein v1.2.3
	github.com/go-chi/chi/v5 v5.0.7
	github.com/go-chi/render v1.0.1
	github.com/go-playground/validator/v10 v10.10.0
	github.com/gofrs/uuid v3.3.0+incompatible
	github.com/golang/mock v1.6.0
	github.com/subosito/gotenv v1.2.0
	github.com/uptrace/bun v1.0.20
	golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2
	golang.org/x/text v0.3.7
)
```
```
version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
       - dependency-name: "dev.azure.com/xxx/xxx-sdk-common-api.git"
```

But the `dev.azure.com/xxx/xxx-sdk-common-api.git`  is not ignored by the dependabot
