### ISSUE TITLE
Failed to create pull request: TypeError: Cannot read properties of null (reading 'pullRequestId')

### ISSUE THREAD

**Issue by Hoang-Minh** [dependabot/dependabot-script#946]
I am trying to setup a CI build pipeline on azure with dependabot.
Here is my yml files:

azure-pipelines.yml:

```
trigger: none
stages:
  - stage: CheckDependencies
    displayName: Check Dependencies
    jobs:
      - job: Dependabot
        displayName: Run Dependabot
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: dependabot@2
            displayName: Run Dependabot
            inputs:
              packageManager: nuget
              targetBranch: dev
              openPullRequestsLimit: 10
```

/.github/dependabot.yml

```
version: 2
updates:
  - package-ecosystem: 'nuget'
    directory: '/'
    target-branch: 'dev'
    open-pull-requests-limit: 10
    ignore:
        - dependency-name: 'Microsoft.Extensions.Caching.SqlServer'
    schedule:
      interval: 'daily'
```

Here is my error:

```
Creating pull request 'Bump FluentAssertions from 6.12.0 to 6.12.1'...
 - Pushing 1 change(s) to branch 'dependabot/nuget/dev/FluentAssertions-6.12.1'...
 - Creating pull request to merge 'dependabot/nuget/dev/FluentAssertions-6.12.1' into 'dev'...
 - Adding dependency metadata to pull request properties...
##[error]Failed to create pull request: TypeError: Cannot read properties of null (reading 'pullRequestId')
TypeError: Cannot read properties of null (reading 'pullRequestId')
    at AzureDevOpsWebApiClient.createPullRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.955/utils/azure-devops/AzureDevOpsWebApiClient.js:191:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DependabotOutputProcessor.process (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.955/utils/dependabot-cli/DependabotOutputProcessor.js:66:42)
    at async DependabotCli.update (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.955/utils/dependabot-cli/DependabotCli.js:101:51)
    at async run (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.955/index.js:72:50)
```

Permissions are given to my Build Service account:

![image](https://github.com/user-attachments/assets/6afd5e30-e02b-4dd2-9e94-93534cf0dff8)

I'm not sure if I miss anything. Everything seems to be correct setup.
Can anyone help ? Thank you.
